# Generated by Django 3.1.6 on 2021-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='poster/', verbose_name='Постер')),
                ('Age', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=50, verbose_name='Возростное ограничение')),
                ('Category', models.CharField(choices=[('Боевик', 'Боевик'), ('Вестерн', 'Вестерн'), ('Гангстерский фильм', 'Гангстерский фильм'), ('Детектив', 'Детектив'), ('Драма', 'Драма'), ('Исторический фильм', 'Исторический фильм'), ('Комедия', 'Комедия'), ('Мелодрама', 'Мелодрама'), ('Музыкальный фильм', 'Музыкальный фильм'), ('Нуар', 'Нуар'), ('Политический фильм', 'Политический фильм'), ('Приключенческий фильм', 'Приключенческий фильм'), ('Сказка', 'Сказка'), ('Трагедия', 'Трагедия'), ('Трагикомедия', 'Трагикомедия')], max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильм',
            },
        ),
    ]
