# Generated by Django 3.1.6 on 2021-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeanceDate', models.DateField(verbose_name='Дата сеанса')),
                ('SeanceTime', models.TimeField(verbose_name='Время сеанса')),
                ('Hall', models.CharField(choices=[('Зал1', 'Зал1'), ('Зал2', 'Зал2')], max_length=50, verbose_name='Зал')),
                ('Price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
